import './VirtualBox/InspectionCard';
import './ID';
import './PastHistory';
import './Enums';
import './SmokingAndDrinking';
import './Table';
import './common';
import './BloodPressure';
import './Abnormal';
import './RiskAssessment';
export { InfectiousDisease } from './RemarkCheckbox';
