declare const _default: {
    '[):]': string;
    '[:D]': string;
    '[;)]': string;
    '[:-o]': string;
    '[:p]': string;
    '[(H)]': string;
    '[:@]': string;
    '[:s]': string;
    '[:$]': string;
    '[:(]': string;
    '[:\'(]': string;
    '[<o)]': string;
    '[(a)]': string;
    '[8o|]': string;
    '[8-|]': string;
    '[+o(]': string;
    '[|-)]': string;
    '[:|]': string;
    '[*-)]': string;
    '[:-#]': string;
    '[:-*]': string;
    '[^o)]': string;
    '[8-)]': string;
    '[(|)]': string;
    '[(u)]': string;
    '[(S)]': string;
    '[(*)]': string;
    '[(#)]': string;
    '[(R)]': string;
    '[({)]': string;
    '[(})]': string;
    '[(k)]': string;
    '[(F)]': string;
    '[(W)]': string;
    '[(D)]': string;
};
export default _default;
