'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
require('./VirtualBox/InspectionCard');
require('./ID');
require('./PastHistory');
require('./Enums');
require('./SmokingAndDrinking');
require('./Table');
require('./common');
require('./BloodPressure');
require('./Abnormal');
require('./RiskAssessment');
var RemarkCheckbox_1 = require('./RemarkCheckbox');
exports.InfectiousDisease = RemarkCheckbox_1.InfectiousDisease;
