import { ctg_exams_analyse_score, _ctg_exams_analyse } from "@lianmed/f_types/lib/obvue/ctg_exams_analyse";
declare type TData = ctg_exams_analyse_score['cstoctdata'];
export declare function Cstoct(_data: TData, analysis: _ctg_exams_analyse['analysis']): {
    bhrscore: import("csstype").AnimationIterationCountProperty;
    ltvvalue: import("csstype").AnimationIterationCountProperty;
    ltvscore: import("csstype").AnimationIterationCountProperty;
    accscore: import("csstype").AnimationIterationCountProperty;
    accvalue: import("csstype").AnimationIterationCountProperty;
    bhrvalue: import("csstype").AnimationIterationCountProperty;
    decscore: import("csstype").AnimationIterationCountProperty;
    decvalue: import("csstype").AnimationIterationCountProperty;
    edscore: import("csstype").AnimationIterationCountProperty;
    edvalue: import("csstype").AnimationIterationCountProperty;
    ldscore: import("csstype").AnimationIterationCountProperty;
    ldvalue: import("csstype").AnimationIterationCountProperty;
    vdscore: import("csstype").AnimationIterationCountProperty;
    vdvalue: import("csstype").AnimationIterationCountProperty;
    sinusoidscore: import("csstype").AnimationIterationCountProperty;
    sinusoidvalue: import("csstype").AnimationIterationCountProperty;
    total: import("csstype").AnimationIterationCountProperty;
    result: import("csstype").AnimationIterationCountProperty;
};
export {};
